### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by Mat2095** [se2p/ps-2019-assignment-02-public-tests#20]
Instead of checking for new commits every 10 minutes it would be a more elegant solutioin to use webhooks.
That way GitHub will send a HTTP(S) request to the "CI"-Server whenever there is a push to a repository. When receiving such a request, the tests are run as before.

Possible hurdles:
- I don't know if webhooks are available for classroom-repositories. I can't set up webhooks for my assignment-repository, maybe the lecturer can, maybe it isn't possible at all.
- GitHub needs some sort of endpoint to send the request, so something like a domain or a static ip. I haven't tried it myself, but ngrok (or something similar) would probably be a good way around that.

**Comment by alessiogambi** [comment]
Sure, "polling is never an option." However, I have no idea how to set up webhooks, and unfortunately it will not be easy to obtain a static ip to receive the requests from github at the faculty.

Anyway, I'll take note of this suggestion and pass it to the others at the chair that are facing similar issues
