### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Mat2095** [se2p/ps-2019-assignment-02-public-tests#21]
Currently, all tests fail on windows, since the expected output contains CRLF line-endings, while the produced line-endings are LF.
One easy solution would be to add the `--strip-trailing-cr` flag to the `diff`-command to ignore line-endings (that might be undesired?).
Another solution would be to add a `.gitattributes` file with` expected.output -text`. That way git won't normalize line-endings from LF to CRLF. However windows-users would have to delete and re-checkout the repository for this to have effect.

**Comment by alessiogambi** [comment]
Hi, I prefer the first solution.
