### ISSUE TITLE
Reuse test scripts for multiple inputs + expected outputs

### ISSUE THREAD

**Issue by marvinkreis** [se2p/ps-2019-assignment-02-public-tests#3]
Since we have these elaborate test scripts it would be nice to be able to reuse them for multiple inputs and expected outputs. Maybe with a folder structure similar to this, the test script could just iterate over the inputs, or get an index as an additional parameter.
```
├── inputs
│   ├── input-1
│   ├── input-2
│   └── input-3
├── expected.outputs
│   ├── expected.output-1
│   ├── expected.output-2
│   └── expected.output-3
├── outputs
│   ├── output-1
│   ├── output-2
│   └── output-3
├── names
│   ├── name-1
│   ├── name-2
│   └── name-3
└── secrets
    ├── secret-1
    ├── secret-2
    └── secret-3
```

**Comment by Mat2095** [comment]
I agree, but I'd prefer the structure "the other way round", like this:
```
├── test-1
│   ├── input
│   ├── expected.output
│   ├── name
│   ├── game.result
│   └── secret.code
├── test-2
│   ├── input
│   ├── expected.output
│   ├── name
│   ├── game.result
│   └── secret.code
└── test-3
    ├── ...
```

with all of the different tests using the same scripts. Basically moving the scripts/assertions/... up one level.

**Comment by alessiogambi** [comment]
I also agree with @Mat2095 because that solution follows the locality principle: all the info/data related to a  tests are in the same place.

**Comment by alessiogambi** [comment]
I consider this issue closed. However, from the proposed changes I see there are few issues to address. I open new issues for them
